prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'app-service'
        metrics_path: '/metrics'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - default  # Specify the namespace where your app pods are running
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod


grafana:
  enabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      editable: true

proxy:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""

