{
 "title": "Key Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "API Resposne Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_response_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "api_error_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Button Clicks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "button_press_total", "legendFormat": "__auto" }
   ]
  }
 ]
}